### PR TITLE
Backport/rocko/secondaries and ci improvement

### PR DESCRIPTION
**Pull request by mike-sul**
oe-selftest hasn't been executed yet

### CODE REVIEW

**Comment by patrickvacek** [comment]
No need to backport a patch and then remove it. :) Also looks like 5ce9387025581813b3db3d2641d8d59c9e7a0d17 has merge markers in it still. However, I'm not sure that or 87d65ec8e82cdc252ad984b06e733bae6155baa9 are desirable/necessary to backport; if you want them, they should be well-tested.

**Comment by mike-sul** [comment]
> No need to backport a patch and then remove it. :) Also looks like [5ce9387](https://github.com/advancedtelematic/meta-updater-raspberrypi/commit/5ce9387025581813b3db3d2641d8d59c9e7a0d17) has merge markers in it still. However, I'm not sure that or [87d65ec](https://github.com/advancedtelematic/meta-updater-raspberrypi/commit/87d65ec8e82cdc252ad984b06e733bae6155baa9) are desirable/necessary to backport; if you want them, they should be well-tested.

I have no idea what all those commits meant so I backported everything and then just removed what's doesn't work in a given branch :)

Would you like me to delete  87d65ec  ?

**Comment by patrickvacek** [comment]
> Would you like me to delete [87d65ec](https://github.com/advancedtelematic/meta-updater-raspberrypi/commit/87d65ec8e82cdc252ad984b06e733bae6155baa9) ?

@lbonn @eu-smirnov Any opinions here? I don't know that code well.

**Comment by lbonn** [comment]
I think 5ce9387 is necessary for having device tree overlays, @eu-smirnov might now a bit more about that indeed since he's been playing with FIT images on rocko recently.

87d65ec seems pretty harmless though. Would be nice to check manually that the info ends up in /proc/cpuinfo as advertised though.

**Comment by mike-sul** [comment]
ok, here is the menu, let's pick up what we would like to digest 

1b54815e356a99680a1643ed591a433073f93984 OTA-2294: WiFi support for RPi: Drivers and systemd service to auto enable WiFi connection
7d4244489c53c04a2a7fc558500098f82eb2864b Add raspberrypi3-64 support
b85f96e11956c07dfb5a2c343dfeb636ee6a7832 dtc: remove patch that has been merged upstream.
a639e8ee8e4329155db37a428b64c68f0ee2fdb9 layer.conf: Add warrior to compatible release series
a1f0ea1f90c1e38233edaf4859630b4f352f0ad6 Add patch for dtc to avoid segmentation fault on Raspberry Pi
dd8e4076a8c709154f71cf4521452d2bed0c6475 Fix patch to apply to u-boot on poky master
5854b4ce21408d117b4592fdadec9b2f295bb7ec Load FIT configuration from the OSTree root fs
6ebdc82876b55f5d278cba8cc990073fb036d29e Patch u-boot to forward board revision and serial to the device tree
13866ddd46a5e42d4d14ee75d68d37abba5af3f6 Fix pipefail issue in GPT PMBR check
e7a46a30e99401a4dd41a5cba2dde71c726c4554 flash-image: fix issues caught by shellcheck.
cb4c9eb8d9b6b36da4a063ec4a233d94d8f95baf flash-image: rpi-basic-image is deprecated. Use core-image-minimal.
8d389af7214e4c8f3274205a2b812748ddbe195a Update reference to ATS Garage to HERE OTA Connect.
2e11b7e5c23f1a6874a911246d7979a7b74b5782 flash-image.sh: add option to force flashing.
43b9d0f3e9819b7deaef0db24e9bf81926ca34eb flash-image.sh: automatically detect and fix GPT size mismatch problem.
a1d822b066697e9a9e2ea68b35722566c551a971 Add rollback support
23d65734a27b5d16d481fd1e7643e620b270ff80 Update layer compatibility to thud.
2b2d6fbc91561d8334af3b1e13b6a3537bdf2df7 Load FIT image ($kernel_image) to $ramdisk_addr_r
afb195c06391e05fa9afea749cf1228ed14b34dd u-boot-otascript: uEnv: Allow booting from non-ext4 filesystems
d55f37951d0cffb37de7c20af02ae58ddfc3be5e Fix boot on Raspberry pi
c6b8cd50aca25aadae42a9a820dcebd977f2c20d u-boot-otascript: uEnv: Do not load initrd separately
38b85ef99b58c1cfd1366d35516bc1ffc5591215 Set layer compatibility version to sumo
5f1e3167547816cccef6955221ea1afe866b7c6c Remove AGL patches
effb9420fe2c8be822977960d4e9fa5b59cb14d9 Fix name of R-Pi image in flash-image.sh
94b315d8f69db0c10aee1fcb8626480c4d8626bd Add support to FIT images and don't use DTB provided by the bootloader

**Comment by mike-sul** [comment]
These two do not work on rocko

7d42444 Add raspberrypi3-64 support
dd8e407 Fix patch to apply to u-boot on poky master

This is

**Comment by mike-sul** [comment]
@lbonn @patrickvacek Please, verify if it contains all required commits. oe-selftest -r updater_raspberrypi passed on bagger. If it's ok, I'll do the same for sumo and thud.

**Comment by patrickvacek** [comment]
Looks like something got mixed up; there are a bunch of redundant commits here. I think most of these are already in rocko.

**Comment by lbonn** [comment]
They are not all in rocko but some of them should stay out of it, since it would break the update process unfortunately. Especially all the changes related to "Do not load initrd separately".

Also there are two commits that touches the dtc recipe: the first one adds a patch and the second removes it. Probably not worth it :)

**Comment by mike-sul** [comment]
I applied the following diff
msul@bagger:~/rocko$ cat rocko.backport.list 
9c0cc4b linux-raspberrypi_%.bbappend: Use wrappers from utils.bbclass
38b85ef Set layer compatibility version to sumo
c6b8cd5 u-boot-otascript: uEnv: Do not load initrd separately
d55f379 Fix boot on Raspberry pi
afb195c u-boot-otascript: uEnv: Allow booting from non-ext4 filesystems
2b2d6fb Load FIT image ($kernel_image) to $ramdisk_addr_r
23d6573 Update layer compatibility to thud.
a1d822b Add rollback support
43b9d0f flash-image.sh: automatically detect and fix GPT size mismatch problem.
2e11b7e flash-image.sh: add option to force flashing.
8d389af Update reference to ATS Garage to HERE OTA Connect.
cb4c9eb flash-image: rpi-basic-image is deprecated. Use core-image-minimal.
e7a46a3 flash-image: fix issues caught by shellcheck.
13866dd Fix pipefail issue in GPT PMBR check
6ebdc82 Patch u-boot to forward board revision and serial to the device tree
5854b4c Load FIT configuration from the OSTree root fs
dd8e407 Fix patch to apply to u-boot on poky master
a1f0ea1 Add patch for dtc to avoid segmentation fault on Raspberry Pi
a639e8e layer.conf: Add warrior to compatible release series
b85f96e dtc: remove patch that has been merged upstream.
7d42444 Add raspberrypi3-64 support
1b54815 OTA-2294: WiFi support for RPi: Drivers and systemd service to auto enable WiFi connection

Which of the above is already in rocko ?

**Comment by mike-sul** [comment]
@patrickvacek @lbonn Please, check it out, I removed the commits that you told me to remove.

**Comment by patrickvacek** [comment]
I suspect that the only thing we actually need/want to backport here (and for sumo) is just the Wifi fixes. The rpi64 patch would be nice, but if it doesn't work, I wouldn't worry too much about it. It looks like everything else is older. Some have already been backported, and a few things we've previously chosen not to backport because it wouldn't work, it would be too complex, or nobody is interested in having it there.

**Comment by mike-sul** [comment]
> I suspect that the only thing we actually need/want to backport here (and for sumo) is just the Wifi fixes. The rpi64 patch would be nice, but if it doesn't work, I wouldn't worry too much about it. It looks like everything else is older. Some have already been backported, and a few things we've previously chosen not to backport because it wouldn't work, it would be too complex, or nobody is interested in having it there.

I'll be more than happy if I need to pick just the wifi patch :)

**Comment by mike-sul** [comment]
yeah, this version of rocko does not work on my RPi.

**Comment by patrickvacek** [comment]
All of the flash-image stuff has already been backported before, and the uEnv bit can be skipped. It would require more integration work than is necessary at this time. So I think that just leaves the wifi bit! Generally, when I do this sort of backporting, I only consider commits added since the last time a backport was done, which in this case should just be the wifi and rpi64 bits.

**Comment by mike-sul** [comment]
So, now just wifi stuff. It does bitbake but doesn't work on my RPi 3 B+.  Will try to fix it...

**Comment by mike-sul** [comment]
@patrickvacek @lbonn This version enables WiFi on my RPi, it would be great if someone verifies it on your side for your RPi.

**Comment by patrickvacek** [comment]
I'll give it a try and see if wifi works.

**Comment by patrickvacek** [comment]
Confirmed that wifi works on my Raspberry Pi 3 Model B V1.2. Thanks!

**Pull request merged**
