### PR TITLE
Backport/sumo/secondaries and ci improvement

### PR DESCRIPTION
**Pull request by mike-sul**
oe-selftest hasn't been executed yet

### CODE REVIEW

**Comment by lbonn** [comment]
This commit was badly rebased: https://github.com/advancedtelematic/meta-updater-raspberrypi/pull/55/commits/397ed91109dba84e43842b6f995fae187c588eac, it shouldn't change the boot process so radically

These commits are empty: https://github.com/advancedtelematic/meta-updater-raspberrypi/pull/55/commits/a611b298a2c5cadd0d8a436bb1ce3e5174647404 and https://github.com/advancedtelematic/meta-updater-raspberrypi/pull/55/commits/599d444ea207f56bf4c1f8ead78c782720d1441d

**Comment by mike-sul** [comment]
> This commit was badly rebased: [397ed91](https://github.com/advancedtelematic/meta-updater-raspberrypi/commit/397ed91109dba84e43842b6f995fae187c588eac), it shouldn't change the boot process so radically
> 
> These commits are empty: [a611b29](https://github.com/advancedtelematic/meta-updater-raspberrypi/commit/a611b298a2c5cadd0d8a436bb1ce3e5174647404) and [599d444](https://github.com/advancedtelematic/meta-updater-raspberrypi/commit/599d444ea207f56bf4c1f8ead78c782720d1441d)



> This commit was badly rebased: [397ed91](https://github.com/advancedtelematic/meta-updater-raspberrypi/commit/397ed91109dba84e43842b6f995fae187c588eac), it shouldn't change the boot process so radically

Unfortunately, that's what happen when the given commit is cherry-picked and some commits are eliminated (those that I was told not to apply also includes changes to this file).

The problem is that the commits that needs to be dropped have changes to this file too.
Anyway, I'll try to apply the version that is in currently in thud and master.

**Comment by mike-sul** [comment]
@lbonn @patrickvacek Please, check out this version.

**Comment by mike-sul** [comment]
@patrickvacek @lbonn This version makes wifi to work for core-image-minimal, it does not work for primary-image though. Please, verify if it works on your RPi.

**Comment by patrickvacek** [comment]
> This version makes wifi to work for core-image-minimal, it does not work for primary-image though. Please, verify if it works on your RPi.

That's annoying! Any clues? Not a high priority, though. Would you like me to test for `core-image-minimal` then?

**Comment by patrickvacek** [comment]
Confirmed that wifi works for my Raspberry Pi 3 Model B V1.2 running a core-image-minimal build. Anything else you needed me to confirm?

**Comment by mike-sul** [comment]
No, thanks, still fighting with enabling of ethernet for thud, wifi does work on it out of box though

**Pull request merged**
