### PR TITLE
Feat/warrior/2019.9 backport

### PR DESCRIPTION
**Pull request by patrickvacek**
This includes support for RPi4, which should get well-tested before merging.

### CODE REVIEW

**Comment by lbonn** [comment]
@Raigi 
I managed to boot a raspberrypi4-64 image with this branch and https://github.com/advancedtelematic/meta-updater/pull/617.

Will also check plain raspberrypi4.

**Comment by Raigi** [comment]
> @Raigi
> I managed to boot a raspberrypi4-64 image with this branch and [advancedtelematic/meta-updater#617](https://github.com/advancedtelematic/meta-updater/pull/617).
> 
> Will also check plain raspberrypi4.

Anything specific you did? I also had this branch + #617 Pr, but it didn't boot up

**Comment by lbonn** [comment]
Also works on raspberrypi4.

```
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <remote fetch="https://github.com" name="github" pushurl="ssh://git@github.com"/>
  <remote fetch="git://git.openembedded.org/" name="openembedded"/>
  <remote fetch="https://git.yoctoproject.org/git/" name="yocto"/>

  <default remote="github" revision="warrior"/>

  <project name="advancedtelematic/meta-updater" path="meta-updater" revision="eb013d282c50618ce44a12c896f7d4862cd2d592" upstream="warrior"/>
  <project name="advancedtelematic/meta-updater-minnowboard" path="meta-updater-minnowboard" revision="8f228913fb21c908f05c0a7d37f2ac190a231db2" upstream="warrior"/>
  <project name="advancedtelematic/meta-updater-qemux86-64" path="meta-updater-qemux86-64" revision="34fb05a6e91ffa4d83b8ef9761abac4c5efa4ea8" upstream="warrior"/>
  <project name="advancedtelematic/meta-updater-raspberrypi" path="meta-updater-raspberrypi" revision="c5fec7c485cb43567bd59a8a75658154252e454a" upstream="warrior"/>
  <project name="meta-intel" remote="yocto" revision="ca26bed652722167b2dbe0042cfc2406029e9c6c" upstream="warrior"/>
  <project name="meta-openembedded" remote="openembedded" revision="a24acf94d48d635eca668ea34598c6e5c857e3f8" upstream="warrior"/>
  <project name="meta-raspberrypi" remote="yocto" revision="5cb49f4d76a311201bd36cf6538e23a59e3d8030" upstream="warrior"/>
  <project name="poky" remote="yocto" revision="4ada58f74c9bb5ab2fd4ef7a0c6ee4219b579d4b" upstream="warrior"/>
</manifest>
```

Nothing special really, except that I had a problem with one sd card that solved itself when I tried another one.

**Comment by Raigi** [comment]
> Also works on raspberrypi4.
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <manifest>
>   <remote fetch="https://github.com" name="github" pushurl="ssh://git@github.com"/>
>   <remote fetch="git://git.openembedded.org/" name="openembedded"/>
>   <remote fetch="https://git.yoctoproject.org/git/" name="yocto"/>
> 
>   <default remote="github" revision="warrior"/>
> 
>   <project name="advancedtelematic/meta-updater" path="meta-updater" revision="eb013d282c50618ce44a12c896f7d4862cd2d592" upstream="warrior"/>
>   <project name="advancedtelematic/meta-updater-minnowboard" path="meta-updater-minnowboard" revision="8f228913fb21c908f05c0a7d37f2ac190a231db2" upstream="warrior"/>
>   <project name="advancedtelematic/meta-updater-qemux86-64" path="meta-updater-qemux86-64" revision="34fb05a6e91ffa4d83b8ef9761abac4c5efa4ea8" upstream="warrior"/>
>   <project name="advancedtelematic/meta-updater-raspberrypi" path="meta-updater-raspberrypi" revision="c5fec7c485cb43567bd59a8a75658154252e454a" upstream="warrior"/>
>   <project name="meta-intel" remote="yocto" revision="ca26bed652722167b2dbe0042cfc2406029e9c6c" upstream="warrior"/>
>   <project name="meta-openembedded" remote="openembedded" revision="a24acf94d48d635eca668ea34598c6e5c857e3f8" upstream="warrior"/>
>   <project name="meta-raspberrypi" remote="yocto" revision="5cb49f4d76a311201bd36cf6538e23a59e3d8030" upstream="warrior"/>
>   <project name="poky" remote="yocto" revision="4ada58f74c9bb5ab2fd4ef7a0c6ee4219b579d4b" upstream="warrior"/>
> </manifest>
> ```
> 
> Nothing special really, except that I had a problem with one sd card that solved itself when I tried another one.
> 
> Did you look at the serial output?

I did, but it didn't do anything, it was just stuck.. also the rpi4 got super heated up.

**Comment by lbonn** [comment]
Though, it seems that the network doesn't come up by default.
This might be what makes it work on master: https://git.openembedded.org/openembedded-core/commit/?id=d87efd14ce0471135c0aa7fd7b5da2808acb9c76, which is not present on warrior.

I'll have a look.

**Pull request merged**
