### PR TITLE
Rename bootfile patch.

### PR DESCRIPTION
**Pull request by patrickvacek**
In a907c3261ef583f898803706cd596d372c6644cb of meta-raspberrypi, the bbfile has been renamed, so we have to rename it here accordingly.

Oddly, it's only in Yocto dunfell right now, but it looks like this will get into master soon, too.

### CODE REVIEW

**Comment by Raigi** [comment]
I am unable to provision a device and I can't really check the device with serial cable.
Anything I am missing?

**Comment by patrickvacek** [comment]
> I am unable to provision a device and I can't really check the device with serial cable.
> Anything I am missing?

I hope not. This should fix the broken build, but I wouldn't have expected anything to change with booting and provisioning. Can you ssh into the device?

**Comment by Raigi** [comment]
> > I am unable to provision a device and I can't really check the device with serial cable.
> > Anything I am missing?
> 
> I hope not. This should fix the broken build, but I wouldn't have expected anything to change with booting and provisioning. Can you ssh into the device?

no, can't do that either, it doesn't appear on network list

**Comment by patrickvacek** [comment]
> no, can't do that either, it doesn't appear on network list

Okay, I guess I'll have to try to reproduce it, then. I'm still trying to fix some issues with qemu and u-boot on master, too.

**Comment by patrickvacek** [comment]
@Raigi thanks for your patience. My microSD card died, but I have another one, so I've finally been able to debug this again. This PR is fine as is, but it turns out that we also need another change in meta-updater as well, which I've submitted as a PR: https://github.com/advancedtelematic/meta-updater/pull/758. Can you try booting with both of these changes?

**Comment by patrickvacek** [comment]
Awesome, thanks!

**Pull request merged**
